# INPUTS
input CustomerDataInput {
  email: String!
}

input CustomerIdInput {
  id: ID!
}

input CustomerInput {
  email: String!
  firstname: String!
  lastname: String!
  telephone: String!
  cpf: String!
  password: String!
  date_of_birth: String!
  gender: Int!
}

# RETURNS
type Customer {
  id: ID!
  email: String!
  firstname: String!
  lastname: String!
  telephone: String!
  cpf: String!
  password: String!
  date_of_birth: String!
  gender: Int!
}

type CreatedCustomer {
  customer: Customer!
}

# QUERIES / MUTATIONS

type Query {
  customerList: [Customer!]!
  customerById(data: CustomerIdInput!): CreatedCustomer!
  customer(data: CustomerDataInput): CreatedCustomer!
}

type Mutation {
  createCustomer(data: CustomerInput!): CreatedCustomer!
}
